### ISSUE TITLE
metadata sweeper

### ISSUE THREAD

**Issue by stdavis** [agrc/sweeper#33]
Was this ever discussed as an option? I'm seeing lots of missing metadata. We'd need to wait until Pro 2.5 is released to be able to have access to it via arcpy.

- [x] Should validate that `summary` is shorter in length than `description`. Moved to: #48
- [x] `purpose` needs to be less than 2048 characters to map to `snippet` in AGOL. Moved to #48.
- [x] Link to data page. Moved to #49

**Comment by steveoh** [comment]
It has not been discussed since you brought it up the last time IIRC. 

I think you should take a crack at it since you have some loose requirements for the AGOL initiative.

https://docs.google.com/document/d/1gUc-pSspPNZgcoaKtV9JZqXrMScP8F23WqbWQAJbC_o/edit#heading=h.xr1uctwau2qt

**Comment by stdavis** [comment]
Idea from @steve: Require links back to gis.utah.gov data pages and possibility open data pages.

**Comment by stdavis** [comment]
Here's the new working doc for standards: https://github.com/agrc/sweeper/issues/33

**Comment by stdavis** [comment]
Closing this in favor of more specific issues...
